### ISSUE TITLE
no declaration file 

### ISSUE THREAD

**Issue by BernardA** [stratiformltd/react-loadable-visibility#14] opened 2018-10-22 09:09 UTC
Getting the error below on Visual Studio Code when attempting to use react-loadable-visibility. 

I was already using react-loadable without this issue. 

     Could not find a declaration file for module 'react-loadable-visibility/react-loadable'. '/Users/BAMAC/Sites/pwa3/node_modules/react-loadable-visibility/react-loadable.js' implicitly has an 'any' type.

I am using npm (6.4.1), react(16.5.2) and webpack(3.8.1) versions.

For whatever it's worth, here's some excerpts of app.js code:

     ......
     import Loadable from 'react-loadable';
    import LoadableVisibility from 'react-loadable-visibility/react-loadable';
    import PrivateRoute from './auth/auth';
    import Header from './pages/common/header/';
    import { Loading } from './tools/functions';

    const HomePage = Loadable({
        loader: () => import('./pages/home/'),
        loading: Loading,
        delay: 100
    });

    const Footer = LoadableVisibility({
        loader: () => import('./pages/common/footer/'),
        loading: Loading,
      })

Additionally, I do have an issue with react-loadable not retrieving files from cache when used with service-worker. I could not find where to report on react-loadable's repository.
I did try SO, without success.

**Comment by tazsingh** [comment] 2018-10-22 20:29
Closing this issue as it's a duplicate of #13 with less information. Github was having some issues which could've caused the other issue to disappear causing a repost of this. Feel free to leave any additional comments on #13.

**Closed as completed by tazsingh** 2018-10-22 20:29 UTC
