### ISSUE TITLE
Not working when component itself has more content to cover visible area

### ISSUE THREAD

**Issue by reactarray** [stratiformltd/react-loadable-visibility#10] opened 2018-05-13 08:21 UTC
i have 2 components
ComponentA & ComponentB

i have added h1 tag in  ComponentA  and img tag ComponentB
both components are included in one main component called App Component
both components have console.log() added
Now
1) when i add lots of `<br />` between both component in App component it first log ComponentA and when i scroll to bottom when ComponentB is visible it logs it in console. which is as expected and works fine
2) now when i remove  those lots of `<br />` added between both component and add that <br /> in ComponentA, it logs both ComponentA & ComponentB in console even when ComponentB is not visible in screen yet.

find attached code with issue ,  check log in chrome console. https://www.screencast.com/t/7kW0kxyLH3

[react-loadable-visibility.zip](https://github.com/stratiformltd/react-loadable-visibility/files/1998255/react-loadable-visibility.zip)

**Comment by tazsingh** [comment] 2018-06-17 18:39
Hi @reactarray, it appears that your loading component doesn't correlate with the size of the component that you're loading. That is, your loading component is a `div` which is quite small.

The library will look to see if those loading components are inside the view port, and then load the underlying loaded component. If you were to change the loading component to add lots of `br` tags in there as well, do you get the behaviour that you're looking for?

I'm closing this issue but feel free to re-open if it doesn't work as intended.

**Closed as completed by tazsingh** 2018-06-17 18:39 UTC

**Comment by reactarray** [comment] 2018-06-22 09:47
@tazsingh yes even after adding lots of br tags its not working as expected, thats why i also attached sample code with this. check attached zip file in earlier comment  https://www.screencast.com/t/zx0chnz1s

**Comment by tazsingh** [comment] 2018-06-25 14:14
Yes I took a look at the sample code. Have you tried changing your `App.js` to:

```js
import React, { Component } from 'react';
import LoadableVisibility from 'react-loadable-visibility/react-loadable'

const LoadableComponentA = LoadableVisibility({
  loader: () => import('./ComponentA'),
  loading() {
    return <div>Loading ComponentA... <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /></div>
  }
});

const LoadableComponentB = LoadableVisibility({
  loader: () => import('./ComponentB'),
  loading() {
    return <div>Loading ComponentB...</div>
  }
});

class App extends Component {
	render(){
		return (
			<div>
				<LoadableComponentA />
				<LoadableComponentB />
			</div>
		)
	}
}

export default App;
```

The element's visibility is based on the `loading` element. Therefore if you want the underlying component to appear based of its dimensions, you'd have to ensure that the `loading` component has the same dimensions.

You can take a look at an example of this on my website:
- https://github.com/stratiformltd/website/blob/master/src/pages/architecture/index.js#L20-L33
- https://github.com/stratiformltd/website/blob/master/src/shared/LoadingSection.js
